### ISSUE TITLE
CAPTURE_CAMERA does not work reliably

### ISSUE THREAD

**Issue by vbier** [vbier/habpanelviewer#26] opened 2019-01-03 16:27 UTC
CAPTURE_CAMERA command fails from time to time without an obvious reason.

This has been reported by sidamos in the HPV forum thread.

**Comment by sidamos** [comment] 2019-01-07 19:14
Today it happened again. Attaching logcat. The command log had a red entry "could not stop preview" and from there on all camera snapshots were grey entries, most of them without further info.
I first thought, it is triggered by doing a camera snapshot while the screen is dim, but I cannot reproduce it this way.
[logcat.txt.gz](https://github.com/vbier/habpanelviewer/files/2733988/logcat.txt.gz)

**Comment by sidamos** [comment] 2019-01-08 16:15
Do you mean the adb log before the red error entry in the command log? This was all of the adb log that I could get. The red error was in the morning and the adb log in the evening.

Thanks for the update, I will install it later today.

**Comment by vbier** [comment] 2019-01-09 05:43
Yes, that's what I meant. The log starts with a stack trace and it would be nice to know what happened before and lead to the exception. Too bad that this is not in the log any more, as I could not fix the problem, but only made sure the next CAPTURE_CAMERA command is still processed after the problem has occurred. Maybe we have more luck next time.

**Comment by sidamos** [comment] 2019-01-10 08:31
I hope that I got it this time. 1 hour ago, the snapshot still worked, but it also resulted in a red entry (could not stop preview) in the command log (which I did not know). Now, the snapshot does not work anymore, resulting in grey entries in the command log. Only the first grey entry has additional info (Vorschau gestartet).
[logcat2.txt.gz](https://github.com/vbier/habpanelviewer/files/2744355/logcat2.txt.gz)

**Comment by vbier** [comment] 2019-01-10 09:06
Have you updated the apk before generating the log?

**Comment by sidamos** [comment] 2019-01-10 09:22
Yes, I have updated the apk yesterday evening.

**Comment by sidamos** [comment] 2019-01-10 09:30
The app just closed by itself when I lost Internet for a while.
[logcat3.txt.gz](https://github.com/vbier/habpanelviewer/files/2744610/logcat3.txt.gz)

**Comment by vbier** [comment] 2019-01-10 10:51
Can you add timestamps to the log messages?

**Comment by sidamos** [comment] 2019-01-10 10:55
I have a Chromebook, connect it and enter "adb logcat >file.txt".

**Comment by vbier** [comment] 2019-01-10 12:23
It looks like you did not have the up-to-date apk installed, as the stack traces do not match the current code. I am not sure if something went wrong when building and uploading the apk, or if the download had the old version cached somewhere.

I just added some more fixes, and have uploaded an updated apk. You can very this by checking the version in the system information. It should have todays date in it.

Can you please add "-v threadtime" next time you generate a log so we get timestamps?

**Comment by sidamos** [comment] 2019-01-11 06:43
Ich have installed the new apk and verified that the date is yesterday. I'll report back if there are issues or not.
Thanks for your continued effort! Very much appreciated.

**Comment by vbier** [comment] 2019-01-11 06:55
No problem. I am happy if someone is willing to help in finding the reason for bugs that I cannot reproduce.

**Comment by sidamos** [comment] 2019-01-13 18:47
Happened again. I got a red entry "could not stop preview" at 15:37:53.
Then at 19:40:34 a grey entry with "Vorschau gestartet". This was the first one that did not work.
Then 3 more grey entries with no further text.
[logcat4.txt.gz](https://github.com/vbier/habpanelviewer/files/2753375/logcat4.txt.gz)

**Comment by vbier** [comment] 2019-01-14 08:37
Okay, time stamps helped to see that the stack trace in the log file is still from December 30th. This explains why it does not match current code.

The problem is that HPV log entries only are in the main log, which seems to be so small it can only hold a few minutes of log entries. It starts at 01-13 19:40:34.665, so all I can see is what HPV is doing at 19:40.

Can you check the size of the log buffer with:
> adb logcat -g

And either increase the size:

> adb logcat -G \<size\>: Set the size of the log ring buffer. Can add K or M at the end to indicate kilobytes or megabytes.

or keep the tablet connected with adb while testing and pipe the log to a file on your PC. To do this start
> adb logcat -v threadtime > logfile.txt
before testing. It collects the complete log in the file logfile.txt without truncating old stuff. Depending on how testing takes the file might grow significantly.

Do you use SCREEN_DIM to turn off the tablet?

**Comment by sidamos** [comment] 2019-01-14 08:43
I can't connect the laptop all the time, because I need it. ;-) I will try to increase the buffer later.

Yes, I use SCREEN_DIM over night and when nobody is at home. But I did not try to capture during dimmed screen times.

**Comment by vbier** [comment] 2019-01-14 08:57
Okay, no need to capture another log. This most likely is the same as https://github.com/vbier/habpanelviewer/issues/30.

**Comment by sidamos** [comment] 2019-01-14 09:41
OK, but I *think* it does not happen always after SCREEN_DIM.

**Comment by vbier** [comment] 2019-01-16 07:07
I have yesterday updated the apk. The user in the other issue already confirmed that it fixed his problem. Can you please update and test once again?

**Comment by sidamos** [comment] 2019-01-16 21:14
I have currently installed the version from 14.01.19 2:19 PM and no error, yet. Although I sometimes see a Toast with "could not stop preview", when directly interacting.

**Comment by sidamos** [comment] 2019-01-17 06:30
OK, the apk from 14.01.19 2:19 PM just had the problem again and I realized that the link above is different now. So, I'll install that one and report back.

**Comment by sidamos** [comment] 2019-01-23 21:13
No problems yet with the latest version.

**Comment by vbier** [comment] 2019-01-24 08:12
That's nice. I am going to integrate the changes to the main branch and create a new release in the next days.

**Comment by vbier** [comment] 2019-01-24 08:12
Do you also have a Fire Tab or is this another device?

**Closed** 2019-01-24 14:05 UTC
Labels: bug

**Comment by sidamos** [comment] 2019-02-20 11:57
Unfortunately, it happens again. This is what I did:
* was running apk 0.9.25pre (05.02.19 2:45 PM) without problems
* saved settings to file
* uninstalled all apps from Fire tablet (incl. Google Play Store)
* reinstalled Google apps, added different Google account
* installed same apk (from file) again
* restored settings from file
* loaded correct dashboard

Now, camera snapshot sometimes works and sometimes does not. If it does not, then I get "Sperre Kamera..., Vorschau gestartet" in the command log.

Attaching logcat from doing this:
* start app
* camera snapshot works
* leave app, close app (wipe from recents menu)
* start app
* make screenshot
* camera snapshot does not work

BTW, capture camera delay was not restored from settings. I am sure, I had set this to 500 and now it was 100 again. I have set it back to 500, but it does not help with the problem.

[logfile.txt.gz](https://github.com/vbier/habpanelviewer/files/2884501/logfile.txt.gz)

**Comment by sidamos** [comment] 2019-02-20 12:06
When I enable the camera preview (which also sometimes does not work because "cannot find front camera") successfully, then I can also make camera snapshots.

**Comment by vbier** [comment] 2019-02-20 12:20
Have you updated the OS and are you sure you installed the same apk? I can't believe that the same code runs now differently on the same device?

**Comment by sidamos** [comment] 2019-02-20 12:30
I take back the statement that it did not save the camera delay. I had set it to 500 on my Nexus 7. 

I did not update the OS. The apk still says the same version and date/time in settings. I think I had enabled Lollipop camera api before and it is still enabled. I restored the correct settings file (checked time and date). I am also baffled about this.

**Comment by sidamos** [comment] 2019-02-20 12:35
The only differences that I know of:
* I did not reinstall Android Web View (but this tablet does not use it anyway)
* I have now a different Google account (can not matter because I install the apk from file)
* previously, I had installed this apk as update to an older apk and this time, I just installed this apk fresh

**Comment by vbier** [comment] 2019-02-20 12:46
Did you test closing the app from the OS menu previously, or did you only dim the screen?

**Comment by sidamos** [comment] 2019-02-20 12:50
It is likely that I did not force close and restart this version of the app previously.

However, in the meantime, I even rebooted the device and I can't get the camera to work again on first start of the apk.

**Comment by vbier** [comment] 2019-02-20 13:05
I have seen this on one of my devices as well. The camera seems to be blocked when force closing the app, but a reboot always made the camera work again. Did you test with a different camera app?

**Comment by sidamos** [comment] 2019-02-20 13:10
Open Camera from the Play Store works fine when HPV does not.

**Comment by vbier** [comment] 2019-02-20 13:39
Does it help to clear the HPV cache in the app settings?

**Comment by sidamos** [comment] 2019-02-20 13:42
No.

**Comment by vbier** [comment] 2019-02-20 14:56
There are two problems, both unrelated to this one. I have written issues for them: #33 and #34.
